vich_uploader:
    db_driver: orm

    mappings:
        media:
            uri_prefix: '%banners_path%'
            upload_destination: '%kernel.project_dir%/public%banners_path%'
        team_crest_image:
            uri_prefix: '%crest_path%'
            upload_destination: '%kernel.project_dir%/public%crest_path%'
        team_photo_image:
            uri_prefix: '%photo_path%'
            upload_destination: '%kernel.project_dir%/public%photo_path%'
        player_photo_image:
            uri_prefix: '%player_photo_path%'
            upload_destination: '%kernel.project_dir%/public%player_photo_path%'
        news_photo_image:
            uri_prefix: '%news_photo_path%'
            upload_destination: '%kernel.project_dir%/public%news_photo_path%'
