version: '3.7'
services:
    mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "${MAILHOG_EXTERNAL_PORT}:8025"
      restart: unless-stopped

    mysql:
      image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
          MYSQL_DATABASE: "${MYSQL_DATABASE}"
          MYSQL_USER: "${MYSQL_USER}"
          MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      ports:
        - "${MYSQL_EXTERNAL_PORT}:3306"
      restart: unless-stopped

    webserver:
      build: .docker/nginx
      volumes:
          - .:/var/www/html
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "${NGINX_EXTERNAL_HTTP_PORT}:80"
       - "${NGINX_EXTERNAL_HTTPS_PORT}:443"
      restart: unless-stopped

    php-fpm:
      build: .docker/php-fpm
      volumes:
          - .:/var/www/html
          - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      restart: unless-stopped

volumes:
    db_data:
